graph LR
  linkStyle default fill:#ffffff

  subgraph diagram ["Sponsorplatz - Containers"]
    style diagram fill:#ffffff,stroke:#ffffff

    7("<div style='font-weight: bold'>Microsoft Entra ID</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>OIDC Identity Provider (Phase<br />1.4)</div>")
    style 7 fill:#999999,stroke:#6b6b6b,color:#ffffff
    8("<div style='font-weight: bold'>Datatrans</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>Online-Payment-Provider<br />(Phase 9.2)</div>")
    style 8 fill:#999999,stroke:#6b6b6b,color:#ffffff
    9("<div style='font-weight: bold'>SMTP-Server</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>Mail-Versand (MailHog dev,<br />prod-SMTP)</div>")
    style 9 fill:#999999,stroke:#6b6b6b,color:#ffffff
    10("<div style='font-weight: bold'>Zefix</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>Schweizer Handelsregister<br />(Stub)</div>")
    style 10 fill:#999999,stroke:#6b6b6b,color:#ffffff
    11("<div style='font-weight: bold'>OCI Object Storage</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>Backup-Ziel + Medien-Storage</div>")
    style 11 fill:#999999,stroke:#6b6b6b,color:#ffffff

    subgraph 12 ["Sponsorplatz"]
      style 12 fill:#ffffff,stroke:#0b4884,color:#0b4884

      13("<div style='font-weight: bold'>Web-Anwendung</div><div style='font-size: 70%; margin-top: 0px'>[Container: Java 21]</div><div style='font-size: 80%; margin-top:10px'>Spring Boot 3.4 + Thymeleaf,<br />server-rendered HTML</div>")
      style 13 fill:#438dd5,stroke:#2e6295,color:#ffffff
      30[("<div style='font-weight: bold'>PostgreSQL 17</div><div style='font-size: 70%; margin-top: 0px'>[Container: Database]</div><div style='font-size: 80%; margin-top:10px'>Persistenz aller<br />Sponsorplatz-Daten</div>")]
      style 30 fill:#2b3674,stroke:#1e2551,color:#ffffff
    end

    13-. "<div>Liest und schreibt via<br />JPA/Hibernate + Flyway</div><div style='font-size: 70%'>[JDBC]</div>" .->30
    13-. "<div>OIDC Authorization-Code-Flow<br />mit PKCE</div><div style='font-size: 70%'></div>" .->7
    13-. "<div>Zahlung initiieren + Webhook<br />empfangen</div><div style='font-size: 70%'></div>" .->8
    13-. "<div>Spring-Mail JavaMailSender</div><div style='font-size: 70%'></div>" .->9
    13-. "<div>ZefixService (heute Stub,<br />Phase X echte API)</div><div style='font-size: 70%'></div>" .->10
    13-. "<div>BackupService Push +<br />MedienAsset-CDN</div><div style='font-size: 70%'></div>" .->11
  end